name: Generate Code from OpenAPI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  generate_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate python asyncio
        uses: hatamiarash7/openapi-generator@v0.3.0
        with:
          openapi-file: openapi.yml
          output-dir: python-asyncio-client
          generator: python
          command-args: --library asyncio
